name: 'Slack Notify'
description: 'This action will send a notification to Slack'
author: 'rtCamp'
inputs:
  service_account_key:  
    description: 'For google auth'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'yellow'
